<a href="https://colab.research.google.com/github/tufte28/MAT-494/blob/main/MAT494_3_7ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

3.7: Neural Networks

In [1]:
import tensorflow as tf

In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 200.0, x_test / 200.0

In [20]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(100, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(20)
])

In [21]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.6841417 , -0.9652959 ,  0.41612262, -1.2012403 , -0.6774023 ,
         0.2048088 ,  0.30325544, -0.43391094,  1.1205227 , -0.01010868,
         0.1179336 ,  0.43705615, -0.04697001,  0.21658   ,  0.33577678,
        -0.30950782,  0.4244152 , -0.01708423,  0.10903049, -0.32312882]],
      dtype=float32)

In [22]:
tf.nn.softmax(predictions).numpy()

array([[0.02309129, 0.01743189, 0.06938842, 0.01376814, 0.02324744,
        0.05617131, 0.06198254, 0.02965665, 0.1403473 , 0.04530822,
        0.05149738, 0.07085627, 0.04366851, 0.05683643, 0.06403144,
        0.03358534, 0.06996622, 0.04499328, 0.05104093, 0.03313097]],
      dtype=float32)

In [23]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()

2.8793492

In [24]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.3219 - accuracy: 0.9051
Epoch 2/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.1533 - accuracy: 0.9545
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1159 - accuracy: 0.9653
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0984 - accuracy: 0.9691
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0872 - accuracy: 0.9725


In [25]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0752 - accuracy: 0.9765 - 520ms/epoch - 2ms/step


[0.0752096101641655, 0.9764999747276306]

In [27]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [28]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 20), dtype=float32, numpy=
array([[4.71831214e-08, 2.23642314e-06, 4.05032324e-06, 1.70918156e-05,
        7.63176397e-11, 1.59581020e-07, 1.04648722e-12, 9.99975920e-01,
        2.00746300e-07, 3.23636556e-07, 4.06718116e-13, 3.13926700e-13,
        3.57057916e-13, 3.72354972e-14, 2.63366369e-13, 2.43689780e-13,
        2.20128522e-13, 1.91944578e-13, 2.00701370e-12, 1.90973946e-13],
       [7.58127872e-09, 3.59735568e-04, 9.99609172e-01, 2.91135402e-05,
        1.82003647e-14, 7.67767744e-07, 4.08555717e-10, 6.05515583e-13,
        1.13972362e-06, 1.49700061e-11, 1.91424745e-15, 2.43350547e-17,
        1.05895947e-16, 7.14655263e-17, 1.69874483e-16, 6.18829433e-17,
        1.53326013e-16, 1.24381958e-16, 1.20593285e-16, 3.65043407e-18],
       [2.18009699e-08, 9.99771416e-01, 8.16398642e-06, 1.31345041e-06,
        2.42541273e-06, 6.80142057e-06, 2.05820816e-05, 1.58053575e-04,
        3.12891316e-05, 5.29568851e-08, 4.92132279e-10, 5.48805945e-10,
        5.135